default_language_version:
    python: python3.9

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black flake8_drf tests
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort flake8_drf tests
        language: python
        types: [python]